### PR TITLE
Add support for promo/coupon codes in Stripe Checkout

### PR DESCRIPTION
**Pull request by signalnerve**
This PR adds support for Stripe's newly-added [promo code feature in Stripe Checkout](https://twitter.com/stripe/status/1291441519585406976). I've defaulted this value to `true` because it's fairly unobtrusive in the UI, and can safely be ignored if a new member subscribes and doesn't have a coupon to use.

The Stripe documentation on adding customer-facing promotion codes:
https://stripe.com/docs/payments/checkout/set-up-a-subscription#coupons

I've tested this with a local installation and found that it adds the promo code UI as expected (see included screenshots with PR). I then completed the checkout process with a coupon and found that it successfully applied the coupon - woohoo!

<details>
  <summary>📷 Screenshots of the new coupon UI when redirected to Stripe Checkout</summary>
  Screen Shot 2020-08-07 at 12 01 33 AM
  Screen Shot 2020-08-07 at 12 01 44 AM
</details>

<details>
  <summary>📷 Screenshots of the coupon being persisted into the invoice and Stripe customer after checking out</summary>
  Screen Shot 2020-08-06 at 11 56 54 PM
  Screen Shot 2020-08-06 at 11 56 37 PM
</details>

One thing worth noting: it doesn't appear that the coupon information shows up in the Members section in Ghost admin, just the pricing (e.g. $50/yearly, but no mention if I use a 100% coupon). Not sure how to solve that one, but being able to view the subscription in Stripe from the link on the member page seems like an acceptable compromise!

BTW, this is the first PR I've submitted to the extended Ghost universe of source code so happy to accept any changes or if there's a different way this should be done that feels better long-term, you're totally OK to close this :) just wanted to explore if I could get it working, and the resulting change was surprisingly straightforward!

### CODE REVIEW

**Comment by signalnerve** [comment]
thinking on this more... maybe setting this to true by default isn't a safe assumption! 

it may be undesirable to show a coupon code field if you don't have any set up for your site. 

i'm unsure how/if it's feasible to pass this down as a config option, but i would imagine the configurable version of this would be something like a "Allow promo/coupon codes" checkbox in Labs -> Members section in the ghost admin. 

let me know what you think! i personally would be happy to have it live in the checkout UI full-time, but played devil's advocate in my head product/UX-wise and can understand why this may not be as straightforward as "this should always be shown" :)

**Comment by JohnONolan** [comment]
Thanks for the PR and the followup thoughts — you hit all the important points. We're probably not ready to have this on by default, yet, but it might be feasible to add initial support behind a config flag.

What do you think @allouis ?

**Comment by matthanley** [comment]
@signalnerve Thanks for the contribution!

I've written up an issue to cover adding a config flag to control this behaviour: TryGhost/Ghost#12111

**Comment by signalnerve** [comment]
Hey all! I've updated this PR with a new commit (https://github.com/TryGhost/Members/pull/194/commits/fa0e8b8d0ff2b1d199dd7b5ec070b8d3323c4ea2) to handle accepting the config value `enableStripePromoCodes` from a config file, as seen here: https://github.com/TryGhost/Ghost/pull/12149

**Review by allouis — APPROVED** [review]

**Pull request merged**
